services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
    env_file:
      - .env